### ISSUE TITLE
Config Options

### ISSUE THREAD

**Issue by squishey123** [bsavage81/bedrock-world-generator#2]
- [ ] It would be amazing to have a command option to modify the number of blocks traveled per tick. If your world is generating quickly with a large simulation distance, you could theoretically bump up the travel distance from 10 to 100 blocks to complete the generation faster.

- [ ] An option to create a custom radius or a different start/end point would also be really nice.

Thank you.

_Note: I tried looking into building it myself with the distance modified changed and had no luck_

**Comment by miqumi** [comment]
_I like your idea! will try doing it~_
Also by building wdym ?
getting the bp into a .mcpack or making the option?

**Comment by squishey123** [comment]
> _I like your idea! will try doing it~_
> Also by building wdym ?
> getting the bp into a .mcpack or making the option?

.mcpack

Dont even remember what I did to try but didn't get very far. Still appreciate the tool as is 😁

**Comment by miqumi** [comment]
Totally forgot about it; Still appreciate the tool as is 😁
